### PR TITLE
UUID

### PR DESCRIPTION
**Pull request by stefans73**
Change mounting from LUM (like sda) to UUID. That makes remounting possible without creating disorders by new LUMs (sda gets sdb, UUID is still the same. Configuration is a bit easier. In config.cfg devices are not needed anymore. Instead of that config.cfg gets a new option for the pattern to recognize USB-devices.
In webUI renamed Repair to Tools and add buttons for mount/umount USB-storages. This will be extended for iOS.

### CODE REVIEW

**Comment by ruebyi** [comment]
Is this the „fix“ I‘m waiting for?

**Comment by stefans73** [comment]
I'm not sure.  Your posted System Info was after broken sync, right? 
That means, the devices stayed in place (sda1/sdb1). But sdb1 was not 
mounted anymore (or at all?). If UUID will be merged, we'll have a 
webUI-based mount-function and maybe get new information...

Did you try Repair -> Check/Repair with the broken cards and your 
storage?

**Comment by ruebyi** [comment]
Yes, that’s how it happened. 

No repair was not for exfat I thought.

**Comment by stefans73** [comment]
Hi, exfat seems to work. Could you try?

-e sudo umount /dev/sdb1:

sudo fsck -a /dev/sdb1:
fsck from util-linux 2.33.1
exfatfsck 1.3.0
Checking file system on /dev/sdb1.
File system version           1.0
Sector size                 512 bytes
Cluster size                 32 KB
Volume size                  29 GB
Used space                 3936 KB
Available space              29 GB
Totally 0 directories and 0 files.
File system checking finished. No errors found.
---
-e sudo umount /dev/sdb1:

sudo fsck /dev/sdb1:
fsck from util-linux 2.33.1
exfatfsck 1.3.0
Checking file system on /dev/sdb1.
File system version           1.0
Sector size                 512 bytes
Cluster size                 32 KB
Volume size                  29 GB
Used space                 3936 KB
Available space              29 GB
Totally 0 directories and 0 files.
File system checking finished. No errors found.
---

**Comment by stefans73** [comment]
Good news, I also have trouble with exfat, so I can investigate 
tonight... ;-)

**Comment by ruebyi** [comment]
„Good“… Thanks o looking into this

**Comment by stefans73** [comment]
My xqd-card-problems are solved by the last bugfix in uuid! :-))) Hope 
it will help you too. In your case there could also exist another 
problem: If unmounted, are the folders /media/storage and /media/source 
empty?

**Comment by dmpop** [comment]
There is a major flaw in the _install-little-backup-box.sh_ script. The following commands specify the working directory:

```
WORKING_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/scripts"
CONFIG="${WORKING_DIR}/config.cfg"
```

The problem is that if you run the installer as described in the README file using the command `curl -sSL https://raw.githubusercontent.com/dmpop/little-backup-box/main/install-little-backup-box.sh | bash`, the entire installation goes wrong because `WORKING_DIR` is _home/user/pi/scripts_

**Comment by dmpop** [comment]
I've fixed it in https://github.com/dmpop/little-backup-box/pull/122/commits/f12025b0808e213a715e15f19633166cc9fcec72

**Comment by dmpop** [comment]
Superseded by https://github.com/dmpop/little-backup-box/pull/125

**Pull request closed without merging**
